<?php

/*·************************************************************************
 * Copyright ©2007-2012 SARA b.v., Amsterdam, The Netherlands
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at <http://www.apache.org/licenses/LICENSE-2.0>
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 **************************************************************************/

/**
 * File documentation (who cares)
 * @package BeeHub
 */

//DAV::header(array('X-My-Header' => 'My Value'));
//exit();

//phpinfo(); exit;
//ob_start("ob_gzhandler");

//header("Transfer-Encoding: chunked");
//header("Content-Type: text/plain; charset=US-ASCII");
//flush();
//echo "5\r\nhello\r\n0\r\n\r\nX-Trail: yes\r\n";
//flush();
//exit();

require_once dirname( dirname(__FILE__) ) . '/webdav-php/lib/dav.php';

//DAV::debug('started!');

/**
 * A MySQL exception
 * @package BeeHub
 */
class BeeHub_MySQL extends Exception {}

/**
 * A deadlock occured: Try again.
 * @package BeeHub
 */
class BeeHub_Deadlock extends BeeHub_MySQL {}

/**
 * Out of resources: maybe later.
 * @package BeeHub
 */
class BeeHub_Timeout extends BeeHub_MySQL {}


/**
 * Just a namespace.
 * @package BeeHub
 */
class BeeHub {


// const REALM = 'BeeHub';
// const USERS_PATH = '/users/';
// const GROUPS_PATH = '/groups/';
// const WHEEL_PATH = '/users/admin';


const PRIV_READ_PROPERTIES = 'http://beehub.nl/ read-properties';
const PRIV_READ_CONTENT    = 'http://beehub.nl/ read-content';

const PROP_PASSWD          = 'http://beehub.nl/ passwd';

  public static $CONFIG;
  

/**
 * A better escapeshellarg.
 * The default PHP version seems not to work for UTF-8 strings...
 * @return string
 * @param string $arg
 */
public static function escapeshellarg($arg) {
  return "'" . str_replace( "'", "'\\''", $arg ) . "'";
}


public static function localPath($path) {
//  $path = DAV::unslashify('root' . $path);
//  $path = str_replace('#', '##', $path);
  return DAV::unslashify( self::$CONFIG['datadir'] . rawurldecode( $path ) );
}


/**
 * @var mysqli
 */
private static $MYSQLI = null;
/**
 * @return mysqli
 * @throws DAV_Status
 */
public static function mysqli() {
  if (self::$MYSQLI === null) {
    self::$MYSQLI = new mysqli(
      BeeHub::$CONFIG['mysql']['host'],
      BeeHub::$CONFIG['mysql']['username'],
      BeeHub::$CONFIG['mysql']['password'],
      BeeHub::$CONFIG['mysql']['database']
    );
    if ( !self::$MYSQLI )
      throw new BeeHub_MySQL(mysqli_connect_error(), mysqli_connect_errno());
  }
  return self::$MYSQLI;
}


public static function escape_string($string) {
  return is_null($string)
    ? 'NULL'
    : '\'' . self::mysqli()->escape_string($string) . '\'';
}


public static function ETag($etag = null) {
  if (is_null($etag)) {
    self::query('INSERT INTO ETag VALUES();');
    $etag = self::mysqli()->insert_id;
    if (!($etag % 100))
      self::query("DELETE FROM ETag WHERE etag < $etag");
  }
  return '"' . trim( base64_encode( pack( 'H*', dechex( $etag ) ) ), '=' ) . '"';
}


/**
 * @param string $query
 * @return void
 * @throws BeeHub_Deadlock|BeeHub_Timeout|BeeHub_MySQL
 */
public static function real_query($query) {
  if (! self::mysqli()->real_query($query)) {
    if (self::mysqli()->errno == 1213)
      throw new BeeHub_Deadlock(self::mysqli()->error);
    if (self::mysqli()->errno == 1205)
      throw new BeeHub_Timeout(self::mysqli()->error);
    throw new BeeHub_MySQL( self::mysqli()->error, self::mysqli()->errno );
  }
}


/**
 * @param string $query
 * @return mysqli_result
 * @throws Exception
 */
public static function query($query) {
  if ( !( $retval = self::mysqli()->query($query) ) ) {
    if (self::mysqli()->errno == 1213)
      throw new BeeHub_Deadlock(self::mysqli()->error);
    if (self::mysqli()->errno == 1205)
      throw new BeeHub_Timeout(self::mysqli()->error);
    throw new BeeHub_MySQL( self::mysqli()->error, self::mysqli()->errno );
  }
  return $retval;
}


/**
 * @return string a uuid, generated by MySQL
 */
public static function uuid() {
  $result = self::query('SELECT UUID();');
  $row = $result->fetch_row();
  return $row[0];
}


public static function best_xhtml_type() {
  return ( false === strstr(@$_SERVER['HTTP_USER_AGENT'], 'MSIE') &&
           false === strstr(@$_SERVER['HTTP_USER_AGENT'], 'Microsoft') ) ?
    'application/xhtml+xml' : 'text/html';
}


/**
 * @todo implement
 */
public static function current_user() {}


} // class BeeHub

BeeHub::$CONFIG = parse_ini_file(
  dirname(dirname(__FILE__)) . DIRECTORY_SEPARATOR . 'config.ini',
  true
);

